### ISSUE TITLE
Installing a module using !pip install results in Permission denied error

### ISSUE THREAD

**Issue by sanjay-saxena** [jupyter-incubator/enterprise_gateway#189]
If Enterprise Gateway is started under `elyra` user, then running `!pip install pixiedust` from a notebook cell that is backed by `Spark 2.1 - Python(YARN Client Mode)` results in `Permission denied` error as shown below:

```
Installing collected packages: mpld3, geojson, astunparse, pixiedust
Exception:
Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/opt/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/opt/anaconda2/lib/python2.7/site-packages/mpld3'
``` 

I presume that this happening because **only** `root` has the write privileges for everything under `/opt` folder but Enterprise Gateway is running as `elyra`.

**Comment by sanjay-saxena** [comment]
The decision has been to do the following:

1. EG should not be running under `root`.
2. To install modules using `!pip` from the notebook cell, the `--user` flag should be provided.

**Comment by sanjay-saxena** [comment]
With `--user` and EG running under user `elyra`, I am able to install the module successfully.

**Comment by huiyiz** [comment]
This was very helpful! Thank you!
