### ISSUE TITLE
Failed to start the kernel

### ISSUE THREAD

**Issue by sanjay-saxena** [jupyter-incubator/enterprise_gateway#190]
Enterprise Gateway 0.7 Dev version running under user `elyra`. Trying to open an existing notebook resulted in a _sporadic_ `Failed to start the kernel` error with the following stack trace:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/notebook/base/handlers.py", line 503, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 75, in post
    type=mtype))
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/nb2kg/managers.py", line 374, in create_session
    session_id, path, name, type, kernel_name,
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/nb2kg/managers.py", line 144, in start_kernel
    'KERNEL_USERNAME': KG_HTTP_USER
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/nb2kg/managers.py", line 49, in fetch_kg
    auth_username=KG_HTTP_USER, auth_password=KG_HTTP_PASS, **kwargs)
  File "/usr/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
HTTPError: HTTP 500: Internal Server Error
``` 

Enterprise Gateway log when this error occurred is attached.

[eg_log.txt](https://github.com/jupyter-incubator/enterprise_gateway/files/1392426/eg_log.txt)

**Comment by kevin-bates** [comment]
Thanks @sanjay-saxena. The log is indicating that two attempts to start the kernel have taken place and the server is now giving up attempting to continue with that kernel.
```
D 2017-10-17 12:50:58.445 EnterpriseGatewayApp] 8: Waiting to connect.  Host: 'pig3', KernelID: '4023418c-b010-4b18-ab16-9c32531db4ea'
[D 2017-10-17 12:51:03.451 EnterpriseGatewayApp] Waiting for KernelID '4023418c-b010-4b18-ab16-9c32531db4ea' to send connection info from host 'pig3' - retrying...
[D 2017-10-17 12:51:03.952 EnterpriseGatewayApp] Sending signal: 15 to target: 28203 on host: 172.16.xxx.xxx
[D 2017-10-17 12:51:04.381 EnterpriseGatewayApp] SIGTERM signal sent to pid: 28203
[E 2017-10-17 12:51:04.732 EnterpriseGatewayApp] KernelID: '4023418c-b010-4b18-ab16-9c32531db4ea' launch timeout due to: Waited too long (40.0s) to get connection file
[W 171017 12:51:04 web:1587] 500 POST /api/kernels (9.98.xxx.xxx): KernelID: '4023418c-b010-4b18-ab16-9c32531db4ea' launch timeout due to: Waited too long (40.0s) to get connection file
[E 171017 12:51:04 web:2063] 500 POST /api/kernels (9.98.xxx.xxx) 45697.98ms
```
This is usually indicative of resource contention within the YARN cluster and there are likely too many applications running at this time.
Please check your YARN cluster for other applications (probably previously started kernels).  If present, terminate or wait for those application to complete, then try to start the kernel again.

**Comment by kevin-bates** [comment]
The other thing to check, which could lead to this (and is more likely actually), is to make sure each of the nodes has a copy of your kernelspecs - since you're using the `DistributedProcessProxy` and "round robin-ing" across the nodes.

**Comment by sanjay-saxena** [comment]
The real issue turned out to be the manual step for deploying the kernels in each of the cluster nodes by editing `spark-cluster-install/roles/notebook/default/main.yml` such that `deploy_kernelspecs_to_workers` is `true` as shown below:

```
  deploy_kernelspecs_to_workers: true

```

**Comment by kevin-bates** [comment]
Thanks @sanjay-saxena.  Just fyi, we mention the need to have the kernelspecs present on all the nodes here: 
http://jupyter-enterprise-gateway.readthedocs.io/en/latest/system-architecture.html#distributedprocessproxy 
and 
http://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started.html#distributedprocessproxy
