### ISSUE TITLE
R kernels fails to execute Spark DF operations because it can't find Rscript

### ISSUE THREAD

**Issue by lresende** [jupyter-incubator/enterprise_gateway#332]
**Code**
```
library(readr)
raw_data <- read_csv("http://s3.amazonaws.com/apache-zeppelin/tutorial/bank/bank.csv")
sparkR.session()
df <- as.DataFrame(raw_data)
head(df)
```

**Exception**
```
Error in handleErrors(returnStatus, conn): org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 4, lresende-elyra-node-1.fyre.ibm.com, executor 1): java.io.IOException: Cannot run program "Rscript": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.apache.spark.api.r.RRunner$.createRProcess(RRunner.scala:353)
	at org.apache.spark.api.r.RRunner$.createRWorker(RRunner.scala:369)
	at org.apache.spark.api.r.RRunner.compute(RRunner.scala:69)
	at org.apache.spark.api.r.BaseRRDD.compute(RRDD.scala:51)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 24 more
```

**Comment by lresende** [comment]
For some reason, Spark is considering the following environment variables to discover the Rscript: `R_SCRIPT_PATH or R_HOME or PATH`. The only thing that seems to properly make Spark R to work is the new spark configuration option spark.sparkr.r.command. The following change in the R launcher seems to make it work properly:

```
sparkConfigList <- list(
spark.executorEnv.R_LIBS_USER=r_libs_user,
spark.rdd.compress="true",
spark.sparkr.r.command="/opt/anaconda2/lib/R/bin/Rscript")
```

**Comment by akchinSTC** [comment]
Instead of writing into the launch script, should just add the configuration into the kernelspec under the SPARK_OPTS?  Just to stay consistent with putting all the anaconda configs in one place. e.g.
`--conf spark.sparkr.r.command=/opt/anaconda2/lib/R/bin/Rscript`
