### ISSUE TITLE
    ModuleNotFoundError: No module named 'yarn_api_client'

### ISSUE THREAD

**Issue by ericdill** [jupyter-incubator/enterprise_gateway#423]
I'm following along on the getting started instructions and am getting a stack trace on the enterprise gateway server when I try and start the `Spark - Python (Yarn cluster mode)` kernel.
```
[E 180827 20:16:21 web:1670] Uncaught exception POST /api/kernels (172.31.53.200)
    HTTPServerRequest(protocol='http', host='ip-172-31-20-241:8889', method='POST', uri='/api/kernels', version='HTTP/1.1', remote_ip='172.31.53.200')
    Traceback (most recent call last):
      File "/home/edill/miniconda/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/edill/miniconda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/edill/miniconda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/edill/miniconda/lib/python3.6/site-packages/kernel_gateway/services/kernels/handlers.py", line 71, in post
        yield super(MainKernelHandler, self).post()
      File "/home/edill/miniconda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/edill/miniconda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/edill/miniconda/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 47, in post
        kernel_id = yield gen.maybe_future(km.start_kernel(kernel_name=model['name']))
      File "/home/edill/miniconda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/edill/miniconda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/edill/miniconda/lib/python3.6/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 28, in start_kernel
        kernel_id = yield gen.maybe_future(super(RemoteMappingKernelManager, self).start_kernel(*args, **kwargs))
      File "/home/edill/miniconda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/edill/miniconda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/edill/miniconda/lib/python3.6/site-packages/kernel_gateway/services/kernels/manager.py", line 81, in start_kernel
        kernel_id = yield gen.maybe_future(super(SeedingMappingKernelManager, self).start_kernel(*args, **kwargs))
      File "/home/edill/miniconda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/edill/miniconda/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/home/edill/miniconda/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/home/edill/miniconda/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/home/edill/miniconda/lib/python3.6/site-packages/enterprise_gateway/services/kernels/remotemanager.py", line 99, in start_kernel
        process_proxy_class = import_item(self.kernel_spec.process_proxy_class)
      File "/home/edill/miniconda/lib/python3.6/site-packages/ipython_genutils/importstring.py", line 31, in import_item
        module = __import__(package, fromlist=[obj])
      File "/home/edill/miniconda/lib/python3.6/site-packages/enterprise_gateway/services/processproxies/yarn.py", line 15, in <module>
        from yarn_api_client.resource_manager import ResourceManager
    ModuleNotFoundError: No module named 'yarn_api_client'
[E 180827 20:16:21 web:2162] 500 POST /api/kernels (172.31.53.200) 14.58ms
```

**Is this a library that I'm supposed to pip install on the host where I'm running enterprise gateway?**

https://pypi.org/project/yarn-api-client/

**Comment by kevin-bates** [comment]
Hi @ericdill - thanks for the issue.  Yes, `yarn-api-client` is the correct library.  Unfortunately, I don't recall it having a presence in anaconda so if you performed a `conda install` (which I suspect was the case), then you may need to explicitly `pip install` into the appropriate env.

Assuming that's the case, would you please update this aspect of the docs with any additional steps for that installation approach?  That would be appreciated.

Also keep in mind that the kernelspecs we provide are samples and massaging of embedded paths, etc. may be required.

**Comment by lresende** [comment]
@ericdill yarn-api-client is not available in conda, and needs to be pip installed as described by @kevin-bates. Having said that, I thought we had taken care of that on the conda requirements.yml but maybe we need to update the conda recipe as well. I will take a look.

**Comment by lresende** [comment]
Conda forge recipe was missing the dependency, as it was not a regular conda package. I have fixed it now, and the following commands get yarn client installed properly now:
```
conda create --yes --name eg python=3.6
source activate eg
pip list | grep yarn
conda install --yes -c conda-forge jupyter_enterprise_gateway
pip list | grep -i yarn
```

```
pip list | grep yarn
yarn-api-client            0.2.3    
```
